name: 'Auto Setup Project Version'
description: 'Setup the maven project version automatically using Tag or commit hash'

outputs:
    selected-tag-or-hash:
        description: 'The validated tag or commit hash'
        value: ${{ steps.git-info.outputs.selected-tag-or-hash }}

runs:
    using: "composite"
    steps:
        -   name: version setup (Tag or Commit Hash)
            id: git-tag-or-commit-hash
            shell: bash
            run: |
                TAG=$(git describe --tags --exact-match 2>/dev/null || echo "")
                if [ -z "$TAG" ]; then
                  GIT_HASH=$(git rev-parse --short HEAD)
                  echo "selected_hash_or_tag=$GIT_HASH" >> $GITHUB_ENV
                else
                  echo "selected_hash_or_tag=$TAG" >> $GITHUB_ENV
                fi

        -   name: Update Maven version with Git tag or hash
            id: mvn-project-version-setup
            shell: bash
            run: |
                ./mvnw versions:set -DnewVersion="${{ env.selected_hash_or_tag }}"
