name: 'Validate Tag Hash'
description: 'validates Tag or Hash to be used as project version in pom'

inputs:
    tag-or-hash:
        required: false
        description: 'Tag or hash to validate'

runs:
    using: "composite"
    steps:
        -   name: Manual version setup
            shell: bash
            if: ${{ inputs.tag-or-hash != ''}}
            run: |
                echo "PROJECT_VERSION=${{ inputs.tag-or-hash }}" >> $GITHUB_ENV

        -   name: Version setup (Tag or Commit Hash)
            shell: bash
            if: ${{ inputs.tag-or-hash == '' }}
            run: |
                TAG=$(git describe --tags --exact-match 2>/dev/null || echo "")
                if [ -z "$TAG" ]; then
                  GIT_HASH=$(git rev-parse --short HEAD)
                  echo "PROJECT_VERSION=$GIT_HASH" >> $GITHUB_ENV
                else
                  echo "PROJECT_VERSION=$TAG" >> $GITHUB_ENV
                fi
