name: 'Maven Publish to Github Packages'
description: 'Deploys artifact with sources and docs to GH Packages'

runs:
    using: "composite"
    steps:
        -   name: Publish to Github Packages
            id: mvn-deploy-gh
            shell: bash
            run: ./mvnw deploy -DskipTests -Dmaven.source.skip=false -Dmaven.javadoc.skip=false
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
