name: 'Cache Maven dependencies'
description: 'Cache Maven dependencies'

runs:
    using: "composite"
    steps:
        -   name: Cache Maven dependencies
            id: mvn-cache
            uses: actions/cache@v4
            with:
                path: ~/.m2
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                    ${{ runner.os }}-maven-
