name: 'Setup Java'
description: 'Download OpenJDK and set up Java'

inputs:
    java_version:
        required: false
        description: 'Java version'
    java_url:
        required: false
        description: 'Url path to java JDK'

runs:
    using: "composite"
    steps:
        -   name: Setup url and java version
            id: setup-versions
            shell: bash
            env:
                # Set up here the java version and url as defaults to use everywhere
                JAVA_VERSION_DEFAULT: "24.0.1"
                JAVA_URL_DEFAULT: "https://download.java.net/java/GA/jdk24.0.1/24a58e0e276943138bf3e963e6291ac2/9/GPL/openjdk-24.0.1_linux-x64_bin.tar.gz"
            run: |
                JAVA_VERSION="${{ inputs.java_version }}"
                JAVA_URL="${{ inputs.java_url }}"
                if [ -z "$JAVA_VERSION" ]; then
                    echo "JAVA_VERSION=${{ env.JAVA_VERSION_DEFAULT }}" >> $GITHUB_ENV
                fi
                if [ -z "$JAVA_URL" ]; then
                    echo "JAVA_URL=${{ env.JAVA_URL_DEFAULT }}"  >> $GITHUB_ENV
                fi

        -   name: Download OpenJDK
            id: download-openjdk
            shell: bash
            run: |
                echo "downloading GNU GPL Licensed OpenJDK version: ${{ env.JAVA_VERSION }} from ${{ env.JAVA_URL }}"
                wget -O $RUNNER_TEMP/java_package.tar.gz "${{ env.JAVA_URL }}"

        -   name: Set up JDK
            id: setup-java
            uses: actions/setup-java@v4
            with:
                distribution: 'jdkfile'
                jdkFile: ${{ runner.temp }}/java_package.tar.gz
                java-version: ${{ env.JAVA_VERSION }}
                architecture: x64

        -   name: Monitor Java vendor
            id: monitor-java-monitor
            shell: bash
            run: |
                echo "Java vendor is identified as: "
                java -XshowSettings:properties -version 2>&1 | grep vendor
