name: 'Setup Maven'
description: 'Setup cache, Repositories Credentials and Project Version in pom'

inputs:
    packages_user:
        required: true
        description: 'Packages user from workflow'
    packages_token:
        required: true
        description: 'Packages token from workflow'
    manual_version_selection:
        required: false
        description: 'Manual selection of a tag or commit hash'

runs:
    using: "composite"
    steps:
        -   name: Configure GitHub Packages Repository credentials for Maven
            shell: bash
            run: |
                mkdir -p ~/.m2
                cat > ~/.m2/settings.xml <<EOF
                <settings>
                    <servers>
                        <server>
                            <id>github</id>
                            <username>${USERNAME}</username>
                            <password>${TOKEN}</password>
                        </server>
                    </servers>
                </settings>
                EOF
            env:
                USERNAME: ${{ inputs.packages_user }}
                TOKEN: ${{ inputs.packages_token }}

        -   name: Cache Maven dependencies
            uses: actions/cache@v4
            with:
                path: ~/.m2
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                    ${{ runner.os }}-maven-

        -   name: Validate Manually Selected Tag or Commit Hash
            uses: ./.github/actions/validate-tag-hash
            if: ${{ inputs.manual_version_selection != '' }}
            with:
                tag-or-hash: ${{ inputs.manual_version_selection }}

        -   name: Version setup (Tag or Commit Hash)
            shell: bash
            run: |
                if [ -n "${{ inputs.manual_version_selection }}" ]; then
                  echo "PROJECT_VERSION=${{ inputs.manual_version_selection }}" >> $GITHUB_ENV
                else
                  TAG=$(git describe --tags --exact-match 2>/dev/null || echo "")
                  if [ -z "$TAG" ]; then
                    GIT_HASH=$(git rev-parse --short HEAD)
                    echo "PROJECT_VERSION=$GIT_HASH" >> $GITHUB_ENV
                  else
                    echo "PROJECT_VERSION=$TAG" >> $GITHUB_ENV
                  fi
                fi

        -   name: Update Maven version with Git tag or hash
            shell: bash
            run: |
                ./mvnw versions:set -DnewVersion="${{ env.PROJECT_VERSION }}"
