name: 'Checkstyle Code Scan'
description: 'Runs Checkstyle scanner on codebase'

inputs:
    fail-on-violations:
        required: false
        description: 'Which files to scan based on checkfile configuration options'
    github-token:
        required: true
        description: 'the github token to authenticate this action'

runs:
    using: "composite"
    steps:
        -   name: Run checkstyle with maven
            id: run-checkstyle-scan
            shell: bash
            env:
                FAIL_FLAG: ${{ inputs.fail-on-violations }}
            run: |
                if [ -z "$FAIL_FLAG" ]; then
                    echo "FAIL_FLAG=true" >> $GITHUB_ENV
                fi
                ./mvnw checkstyle:check -Dcheckstyle.failOnViolation="${{ env.FAIL_FLAG }}"

        -   name: Upload SARIF to GitHub Security tab
            uses: github/codeql-action/upload-sarif@v3
            with:
                sarif_file: target/checkstyle-result.sarif
                category: checkstyle
                token: ${{ inputs.github-token }}
