name: 'Setup Maven'
description: 'Setup cache, Repositories Credentials and Project Version in pom'

inputs:
    packages_user:
        required: true
        description: 'Packages user from workflow'
    packages_token:
        required: true
        description: 'Packages token from workflow'

runs:
    using: "composite"
    steps:
        -   name: Configure GitHub Packages Repository credentials for Maven
            shell: bash
            run: |
                mkdir -p ~/.m2
                cat > ~/.m2/settings.xml <<EOF
                <settings>
                    <!-- Server configurations -->
                    <servers>
                    <!-- GitHub Package Registry server configuration -->
                        <server>
                            <id>github</id>
                            <username>${USERNAME}</username>
                            <password>${TOKEN}</password>
                        </server>
                    </servers>

                    <!-- This profiles section is to include other repositories / registries by default in all projects -->
                    <profiles>
                        <profile>
                            <id>github-packages</id>
                            <!-- Additional Repositories -->
                            <repositories>
                                <repository>
                                    <id>github</id>
                                    <name>GitHub Packages</name>
                                    <url>https://maven.pkg.github.com/bmc-anvil/*</url>
                                </repository>
                            </repositories>
                        </profile>
                    </profiles>

                    <!-- Activate the profile by default to get all additional repositories -->
                    <activeProfiles>
                        <activeProfile>github-packages</activeProfile>
                    </activeProfiles>
                </settings>
                EOF
            env:
                USERNAME: ${{ inputs.packages_user }}
                TOKEN: ${{ inputs.packages_token }}
