name: 'Setup Maven'
description: 'Setup cache, Repositories Credentials and Project Version in pom'

inputs:
    packages_user:
        required: true
        description: 'Packages user from workflow'
    packages_token:
        required: true
        description: 'Packages token from workflow'

runs:
    using: "composite"
    steps:
        -   name: Configure GitHub Packages Repository credentials for Maven
            shell: bash
            run: |
                mkdir -p ~/.m2
                cat > ~/.m2/settings.xml <<EOF
                <settings>
                    <servers>
                        <server>
                            <id>github</id>
                            <username>${USERNAME}</username>
                            <password>${TOKEN}</password>
                        </server>
                    </servers>
                </settings>
                EOF
            env:
                USERNAME: ${{ inputs.packages_user }}
                TOKEN: ${{ inputs.packages_token }}

        -   name: Cache Maven dependencies
            uses: actions/cache@v4
            with:
                path: ~/.m2
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                    ${{ runner.os }}-maven-
