name: 'Maven build and verify'
description: 'Builds and verifies a project'

inputs:
    continue-on-error:
        description: 'allows to continue on build / verification errors'
        required: false

runs:
    using: "composite"
    steps:
        -   name: maven build and verify
            id: mvn-build-verify
            continue-on-error: ${{inputs.continue-on-error || true }}
            shell: bash
            run: ./mvnw clean verify
