name: manual-deploy
on:
    workflow_call:
        inputs:
            tag-or-hash:
                description: "Git Tag or commit hash to deploy"
                required: true
                type: string

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            -   name: checkout the repository
                uses: actions/checkout@v4

            -   name: Validate input tag or commit hash
                id: validate-tag-commit-hash
                uses: ./.github/actions/validate-tag-or-commit-hash
                with:
                    tag-or-hash: ${{ github.event.inputs.tag-or-hash }}

            -   name: Setup Java
                uses: ./.github/actions/setup-java

            -   name: Cache Maven dependencies
                uses: actions/cache@v4
                with:
                    path: ~/.m2
                    key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                    restore-keys: |
                        ${{ runner.os }}-maven-

            -   name: build and test
                continue-on-error: true
                run: ./mvnw clean verify

            -   name: Update Maven version
                run: ./mvnw versions:set -DnewVersion="${{ steps.validate-tag-commit-hash.outputs.selected-tag-or-hash }}"

            -   name: Publish to Github Packages
                run: ./mvnw deploy -DskipTests -Dmaven.source.skip=false -Dmaven.javadoc.skip=false
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
