name: publish-package
on:
    workflow_call:
        inputs:
            tag-or-hash:
                description: "Optionally specify a Git Tag or commit hash to deploy"
                required: false
                type: string
            java_version:
                required: false
                description: 'Java version'
                type: string
            java_url:
                required: false
                description: 'Url path to java JDK'
                type: string

jobs:
    publish-package:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            -   name: Checkout the repository
                uses: actions/checkout@v4

            -   name: Setup Java
                uses: ./.github/actions/setup-java
                with:
                    java_version: ${{inputs.java_version}}
                    java_url: ${{inputs.java_url}}

            -   name: Setup Maven
                uses: ./.github/actions/setup-maven
                with:
                    packages_user: ${{ secrets.PACKAGES_USER }}
                    packages_token: ${{ secrets.PACKAGES_TOKEN_RW }}
                    manual_version_selection: ${{ inputs.tag-or-hash }}

            -   name: Build and Test
                continue-on-error: true
                run: ./mvnw clean verify

            -   name: Publish to Github Packages
                run: ./mvnw deploy -Pdeployable-jar
                env:
                    GITHUB_TOKEN: ${{ secrets.PACKAGES_TOKEN_RW }}
