name: publish-package
on:
    workflow_call:
        inputs:
            tag-or-hash:
                description: "Optionally specify a Git Tag or commit hash to deploy"
                required: false
                type: string
            java_version:
                required: false
                description: 'Java version'
                type: string
            java_url:
                required: false
                description: 'Url path to java JDK'
                type: string
        secrets:
            PACKAGES_USER:
                required: true
                description: 'Packages user from workflow'
            PACKAGES_TOKEN_RW:
                required: true
                description: 'Packages token from workflow'

jobs:
    publish-package:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            -   name: Checkout the repository
                uses: actions/checkout@v4

            -   name: Setup Java
                uses: bmc-anvil/bmc-devops/.github/actions/setup-java@master
                with:
                    java_version: ${{inputs.java_version}}
                    java_url: ${{inputs.java_url}}

            -   name: Setup Maven
                uses: bmc-anvil/bmc-devops/.github/actions/setup-maven@master
                with:
                    packages_user: ${{ secrets.PACKAGES_USER }}
                    packages_token: ${{ secrets.PACKAGES_TOKEN_RW }}
                    manual_version_selection: ${{ inputs.tag-or-hash }}

            -   name: Checkstyle
                uses: bmc-anvil/bmc-devops/.github/actions/code-quality-checkstyle@master
                with:
                    fail-on-violations: 'false'

            -   name: Build and Test
                continue-on-error: true
                run: ./mvnw clean verify

            -   name: Publish to Github Packages
                run: ./mvnw deploy -Pdeployable-jar
                env:
                    GITHUB_TOKEN: ${{ secrets.PACKAGES_TOKEN_RW }}
