name: Qodana
on:
    workflow_call:

jobs:
    qodana:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
            checks: write
        steps:
            -   uses: actions/checkout@v4
                with:
                    ref: ${{ github.event.pull_request.head.sha }}
                    fetch-depth: 0
            -   name: 'Qodana Code Quality Scan'
                uses: JetBrains/qodana-action@v2024.3
                env:
                    QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
